# Generated by Django 3.0.4 on 2020-06-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commando',
            name='role',
            field=models.CharField(choices=[('1', 'Guns'), ('2', 'FST'), ('3', 'MT'), ('4', 'TACP'), ('5', 'BQMS'), ('6', 'BSM'), ('7', 'BC')], max_length=6),
        ),
    ]
