# Generated by Django 3.0.4 on 2020-06-04 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200603_2327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Profile',
        ),
    ]
