# Generated by Django 3.0.4 on 2020-06-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200625_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Guns', 'Guns'), ('PC', 'PC'), ('FST', 'FST'), ('MT', 'MT'), ('TACP', 'TACP'), ('BQMS', 'BQMS'), ('BSM', 'BSM'), ('BC', 'BC')], max_length=6),
        ),
    ]
