# Generated by Django 3.0.4 on 2020-06-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200628_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_number',
            field=models.CharField(default='00000000', max_length=12),
        ),
    ]
