# Generated by Django 3.0.4 on 2020-06-06 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('coverpic', models.ImageField(upload_to='')),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 6, 23, 5, 53, 725779, tzinfo=utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='albums/<function album_folder at 0x00000136A5E5BA60>')),
                ('thumb', models.ImageField(upload_to='albums/<function album_folder at 0x00000136A5E5BA60>/thumbs')),
                ('caption', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 6, 23, 5, 53, 727780, tzinfo=utc))),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albums.Album')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 6, 23, 5, 53, 728781, tzinfo=utc))),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='albums.AlbumPhoto')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
