# Generated by Django 3.0.4 on 2020-06-07 00:32

import albums.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='coverpic',
            field=models.ImageField(upload_to=albums.models.coverpic_path),
        ),
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 0, 32, 24, 308715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ImageField(upload_to='albums/<function album_folder at 0x000001F663D44DC0>'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='thumb',
            field=models.ImageField(upload_to='albums/<function album_folder at 0x000001F663D44DC0>/thumbs'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 0, 32, 24, 309720, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 0, 32, 24, 310715, tzinfo=utc)),
        ),
    ]
