# Generated by Django 3.0.4 on 2020-06-07 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20200607_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 6, 2, 21, 303519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ImageField(upload_to='albums/<function album_folder at 0x000001687431E700>'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='thumb',
            field=models.ImageField(upload_to='albums/<function album_folder at 0x000001687431E700>/thumbs'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 6, 2, 21, 305521, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 6, 2, 21, 306521, tzinfo=utc)),
        ),
    ]
