# Generated by Django 3.0.4 on 2020-06-07 06:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20200607_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 6, 3, 53, 730029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ImageField(upload_to='albums/<function album_folder at 0x000002207D51E700>'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='thumb',
            field=models.ImageField(upload_to='albums/<function album_folder at 0x000002207D51E700>/thumbs'),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 6, 3, 53, 732020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 6, 3, 53, 734021, tzinfo=utc)),
        ),
    ]
