# Generated by Django 3.0.4 on 2020-06-07 08:07

import albums.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20200607_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 8, 7, 35, 758054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=models.ImageField(upload_to=albums.models.album_folder),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='thumb',
            field=models.ImageField(upload_to=albums.models.thumb_folder),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 8, 7, 35, 759054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 7, 8, 7, 35, 760054, tzinfo=utc)),
        ),
    ]
