# Generated by Django 3.0.4 on 2020-06-13 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0022_auto_20200613_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 11, 40, 36, 872986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 11, 40, 36, 873986, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 11, 40, 36, 874985, tzinfo=utc)),
        ),
    ]
