# Generated by Django 3.0.4 on 2020-06-13 18:18

import albums.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0024_auto_20200613_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumphoto',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='album',
            name='coverpic',
            field=stdimage.models.StdImageField(upload_to=albums.models.coverpic_path),
        ),
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 18, 18, 29, 921072, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='photo',
            field=stdimage.models.StdImageField(upload_to=albums.models.album_folder),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 18, 18, 29, 922076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 18, 18, 29, 923076, tzinfo=utc)),
        ),
    ]
