# Generated by Django 3.0.4 on 2020-06-19 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0026_auto_20200613_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 15, 10, 20, 407451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 15, 10, 20, 408451, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 15, 10, 20, 410452, tzinfo=utc)),
        ),
    ]
