# Generated by Django 3.0.4 on 2020-06-26 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0035_auto_20200626_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 8, 1, 36, 674762, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 8, 1, 36, 675764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 8, 1, 36, 676764, tzinfo=utc)),
        ),
    ]
