# Generated by Django 3.0.4 on 2020-06-28 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0038_auto_20200626_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 17, 41, 35, 605195, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 17, 41, 35, 606196, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 17, 41, 35, 608196, tzinfo=utc)),
        ),
    ]
