# Generated by Django 3.0.4 on 2020-06-19 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('image', models.ImageField(default='idea_pictures/idea_default.jpeg', upload_to='idea_pictures')),
                ('slug', models.SlugField()),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 19, 15, 10, 20, 414454, tzinfo=utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 19, 15, 10, 20, 415454, tzinfo=utc))),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideacomments', to='ideas.Idea')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
