# Generated by Django 3.0.4 on 2020-06-25 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20200625_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 9, 7, 691635, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 9, 7, 692636, tzinfo=utc)),
        ),
    ]
