# Generated by Django 3.0.4 on 2020-06-26 07:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0007_auto_20200626_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 7, 45, 31, 421672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideacomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 7, 45, 31, 422681, tzinfo=utc)),
        ),
    ]
