# Generated by Django 3.0.4 on 2020-06-28 17:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_auto_20200626_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 17, 41, 35, 611195, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 17, 41, 35, 612196, tzinfo=utc)),
        ),
    ]
