# Generated by Django 3.0.4 on 2020-06-28 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0014_auto_20200628_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 20, 58, 1, 410902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 20, 58, 1, 411903, tzinfo=utc)),
        ),
    ]
