# Generated by Django 3.0.4 on 2020-06-29 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0017_auto_20200628_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 7, 6, 6, 557087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 7, 6, 6, 558089, tzinfo=utc)),
        ),
    ]
