# Generated by Django 3.0.4 on 2020-06-10 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200610_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='noticecomment',
            options={'ordering': ['time']},
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 20, 18, 10, 669662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 20, 18, 10, 820122, tzinfo=utc)),
        ),
    ]
