# Generated by Django 3.0.4 on 2020-06-10 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200610_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='noticecomment',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 20, 19, 26, 433627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 20, 19, 26, 610817, tzinfo=utc)),
        ),
    ]
