# Generated by Django 3.0.4 on 2020-06-11 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200610_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='notice_pictures/notice_default.jpeg', upload_to='notice_pictures'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 8, 35, 9, 477771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 11, 8, 35, 9, 610263, tzinfo=utc)),
        ),
    ]
