# Generated by Django 3.0.4 on 2020-06-13 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200613_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 20, 26, 53, 848826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 20, 26, 54, 74895, tzinfo=utc)),
        ),
    ]
