# Generated by Django 3.0.4 on 2020-06-22 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200619_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 8, 59, 58, 341769, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 8, 59, 59, 386546, tzinfo=utc)),
        ),
    ]
