# Generated by Django 3.0.4 on 2020-06-25 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200622_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 4, 41, 81821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 20, 4, 41, 257875, tzinfo=utc)),
        ),
    ]
