# Generated by Django 3.0.4 on 2020-06-26 21:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200626_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 21, 47, 6, 678412, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 21, 47, 7, 17495, tzinfo=utc)),
        ),
    ]
