# Generated by Django 3.0.4 on 2020-06-28 20:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0024_auto_20200628_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 20, 18, 54, 914464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 20, 18, 55, 85510, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='CustomEmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=200, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(verbose_name='Message')),
                ('time', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 20, 18, 55, 85510, tzinfo=utc))),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailstoadmin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
