# Generated by Django 3.0.4 on 2020-06-28 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200628_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemailmessage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 20, 58, 1, 377894, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 20, 58, 1, 203850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 20, 58, 1, 376894, tzinfo=utc)),
        ),
    ]
