# Generated by Django 3.0.4 on 2020-06-28 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200628_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemailmessage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 21, 11, 28, 551876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 21, 11, 28, 364832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 21, 11, 28, 550876, tzinfo=utc)),
        ),
    ]
