# Generated by Django 3.0.4 on 2020-06-29 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200629_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemailmessage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 7, 10, 32, 761777, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 7, 10, 32, 627831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 7, 10, 32, 760776, tzinfo=utc)),
        ),
    ]
